CREATE TABLE bookRequests(
	USER VARCHAR(40) NOT NULL,
	book CHAR(13) NOT NULL,
	date_requested DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (USER, book));
	FOREIGN KEY (USER) REFERENCES users(loginName),
	FOREIGN KEY (book) REFERENCES books(isbn))