CREATE TABLE commentRatings(
	score INT(1) NOT NULL,
	COMMENT INT NOT NULL,
	USER VARCHAR(40) NOT NULL,
	PRIMARY KEY (COMMENT, USER),
	FOREIGN KEY (COMMENT) REFERENCES comments(commentID),
	FOREIGN KEY (USER) REFERENCES users(loginName))
	